-- Copy TPC-H SF1 sample tables into DBT_DYNAMIC_TABLES.TPCH_SF1 and enable change tracking (required for dynamic tables)
-- Co-authored with CoCo

-- Sample data lives in a share, so CLONE / direct change_tracking is not possible.
-- Copy each table individually, then enable CHANGE_TRACKING on the local copies.
CREATE SCHEMA IF NOT EXISTS DBT_DYNAMIC_TABLES.TPCH_SF1;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.REGION AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.REGION SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.NATION AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.NATION SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.CUSTOMER AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.CUSTOMER SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.SUPPLIER AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.SUPPLIER SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.PART AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.PART SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.PARTSUPP AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.PARTSUPP SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.ORDERS AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.ORDERS SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.LINEITEM AS
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
ALTER TABLE DBT_DYNAMIC_TABLES.TPCH_SF1.LINEITEM SET CHANGE_TRACKING = TRUE;
